// index.html generator page
'use strict';

// MAKE A HEADER BAR WITH A LOGO
// PUT A NAVIGATION BAR
// MAKE A PURDY THING HERE
// FOLLOWED BY SOME OTHER STUFF
// PUT SOME CONTENT IN
// MAYBE PUT A FOOTER AT THE BOTTOM
// ADD IN SOME NICE CRAP FOR PEOPLE TO LIKE


// HEAD
    // LOGO
    // NAV BAR
// BODY
    // LOCATIONS
    // HOURS
// FOOTER
    // SOMETHING NICE
